name: Deploy to AWS Lambda

on:
  push:
    branches:
      - 'release/*'  # This specifies that the workflow will trigger on any branch that starts with 'release/'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Package Lambda function
        run: zip -r function.zip index.js

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to AWS Lambda
        run: |
          if [ "${{ github.ref }}" = "refs/heads/release/prod" ]; then
            aws lambda update-function-code \
              --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_PROD }} \
              --zip-file fileb://function.zip \
              --region ${{ secrets.AWS_REGION }}
          elif [ "${{ github.ref }}" = "refs/heads/release/stage" ]; then
            aws lambda update-function-code \
              --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_STAGE }} \
              --zip-file fileb://function.zip \
              --region ${{ secrets.AWS_REGION }}
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
