name: Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (prod, stage)'
        required: true
        default: 'stage'
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'  # Specify your default branch here

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}  # Check out the specified branch

    - name: Set up AWS CLI
      run: |
        choco install awscli || exit 1

    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" || exit 1
        aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" || exit 1
        aws configure set region "${{ secrets.AWS_REGION }}" || exit 1

    - name: Zip the function code
      run: |
        Compress-Archive -Path * -DestinationPath Function.zip

    - name: Deploy to Lambda
      run: |
        $envName = "${{ github.event.inputs.environment }}"
        if ($envName -eq 'prod') {
          $functionName = "${{ secrets.AWS_LAMBDA_FUNCTION_PROD }}"
        } elseif ($envName -eq 'stage') {
          $functionName = "${{ secrets.AWS_LAMBDA_FUNCTION_STAGE }}"
        } else {
          Write-Host "Invalid environment specified. Use 'prod', or 'stage'."
          exit 1
        }

        aws lambda update-function-code --function-name $functionName --zip-file fileb://Function.zip || exit 1

    - name: Clean up
      run: |
        Remove-Item Function.zip -Force
