name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        choco install awscli

    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws configure set region "${{ secrets.AWS_REGION }}"

    - name: Zip the function code
      run: |
        Compress-Archive -Path * -DestinationPath Function.zip

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name "${{ secrets.AWS_LAMBDA_FUNCTION_PROD }}" --zip-file fileb://function.zip
